Feature/gd 165 add xml documentation
IT-Siberians/WalletMicroservice pull request #2
Opened 2024-08-20 11:11 UTC by m-a-ilnitsky

GD-62 Created solution. Added domain entities, value objects, exceptions
GD-62 Renamed solution
GD-62 Added explicit using, and small fixes
GD-103 Added in-memory repository
GD-154 Added EF repository
GD-163 Simplified the properties of entities
GD-165 Added xml-documentation to domain and common classes

2024-08-20 11:43 UTC, Barmalej24 approved these changes
Код понравился, есть вопрос по удалению

2024-08-20 11:43 UTC, Barmalej24 commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        _dbContext.Remove(entity);
не предусмотренно мягкое удаление?

2024-08-20 13:04 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        _dbContext.Remove(entity);
Хороший вопрос.
Совсем забыл про это.
Сделал просто в общем виде.
По идее нужен еще один интерфейс для удаляемых сущностей и разделение интерфейсов репозиториев

2024-08-20 13:08 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        _dbContext.Remove(entity);
Но в целом в кошельке и в архиве скорее всего вообще не должно быть удаления, даже мягкого

2024-08-23 04:28 UTC, NikeTorchwood commented on src/Auction.WalletMicroservice.Infrastructure.EntityFramework/ApplicationDbContext.cs
> +    public DbSet<Freezing> Freezings { get; set; }
Freezings не совсем очевидное имя, возможно есть смысл изменить

2024-08-23 05:11 UTC, NikeTorchwood commented on src/Auction.WalletMicroservice.Infrastructure.EntityFramework/Configurations/FreezingConfiguration.cs
> +        builder.HasOne(f => f.Bill).WithMany("_freezings");
могу ошибаться, но как мне кажется стоит либо пересмотреть Domain слой, либо какой то другой способ, но здесь не стоит использовать прямое обращение по имени(магические элементы - повышает вероятность ошибки, опечатки)

2024-08-23 05:13 UTC, NikeTorchwood commented on src/Auction.WalletMicroservice.Infrastructure.EntityFramework/Configurations/FreezingConfiguration.cs
> +        builder.HasOne(f => f.Bill).WithMany("_freezings");
как вариант если не избежать, хотя бы константой выписать название поля, там несколько таких примеров

2024-08-23 05:14 UTC, NikeTorchwood commented on src/Auction.WalletMicroservice.Infrastructure.EntityFramework/Configurations/TransferConfiguration.cs
> +        builder.HasOne(t => t.FromBill).WithMany("_transfers");
аналогично тому что выше

2024-08-23 05:26 UTC, NikeTorchwood approved these changes
хороший код
из того чтобы я изменил, мне не очевидно название Freezings(даже студия подчеркивает что нет такого слова) и не нравится магические фразы в файлах конфигурации EF, ну и надо хоть какой-то функциональный код добавить, потому что протестировать код на работоспособность нет возможности.

2024-08-23 10:17 UTC, oleggolen commented on src/Infrastructure/Auction.WalletMicroservice.Infrastructure.RepositoriesImplementations/InMemory/InMemoryRepository.cs
> +    where TEntity : class, IEntity<Guid>;
Зачем нужен этот класс, если есть не абстрактный точно такой же класс? Его просто можно убрать, а от того класса наследоваться и перегружать методы

2024-08-23 10:18 UTC, oleggolen commented on src/Infrastructure/Auction.WalletMicroservice.Infrastructure.RepositoriesImplementations/Ef/EfRepository.cs
> +    where TEntity : class, IEntity<Guid>;
Зачем нужен этот класс, если есть не абстрактный точно такой же класс? Его просто можно убрать, а от того класса наследоваться и перегружать методы

2024-08-23 11:12 UTC, oleggolen requested changes
В целом достаточно хороший, рабочий код. Очень подробные комментарии, реализованные репозитории, много слоёв абстракции и реализованная логика доменного слоя. Стоит убрать лишние слои абстракции за их ненадобностью, использовать более подходящие по смыслу системные исключения вместо своих собственных, полностью дублирующих системные, дописать логику ValueObject деньги, чтобы не перегружать код других сущностей, а также более внимательно отнестить к проверки на фомат данных в деньгах. Очень надеюсь, что мои комментарии помогут писать лигко читаемый и понимаемый код и не делать лишней работы, чтобы доманный слой был очень понятным и простым

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/IEntity.cs
> +    where TKey : notnull, IEquatable<TKey>
Добавить проверку на примитивный тип для корректной работы базы данных

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/IEntity.cs
> +public interface IEntity<TKey>
Добавить модификатор out

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +    where TKey : notnull, IEquatable<TKey>
Добавить проверку на примитивный тип для корректной работы базы данных

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +        Username = username ?? throw new ArgumentNullValueException(nameof(username));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractPerson.cs
> +        Username = username ?? throw new ArgumentNullValueException(nameof(username));
Лучше использовать более конкретное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractLot.cs
> +        Description = description ?? throw new ArgumentNullValueException(nameof(description));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Entities/AbstractLot.cs
> +        Title = title ?? throw new ArgumentNullValueException(nameof(title));
Лучше использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/RepositoriesAbstractions/IRepository.cs
> +    where TKey : notnull, IEquatable<TKey>
Выполнить проверку на примитивный тип для корректной работы базы данных

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/RepositoriesAbstractions/IRepository.cs
> +    Task AddAsync(TEntity entity);
Лучше возвращать из метода хоть что-то, потому что клиентскому методу нужен хотя бы Id только что добавленной сущности

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/Money.cs
> +            if (value < 0) throw new MoneyValueException(value);
Так как тут вещественное число необходимо сделать ещё проверку на формат, так как возможен вариант передачи 0.0000001 копейки, что невозмоно в реальности

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
> +        if (validator == null) throw new ArgumentNullValueException(nameof(validator));
Проверка врд ли имеет смысл, так как это передаётся только в классах-наследниках, а там вряд ли получится передать null, а если и получится, то сразу видно будет

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
> +        if (value == null) throw new ArgumentNullValueException(nameof(value));
Использовать более конкретное доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
> +    }
Добавил бы ещё перегрузки операторов == и !=

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        _dbContext.Remove(entity);
Не вижу ничего плохого в жёстком удалении в учебном проекте

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        await _dbContext.SaveChangesAsync();
Вернуть созданный объект или хотя бы Id

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +    }
Не очень понятен смысл метода

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +            .FirstOrDefaultAsync(e => e.Id.Equals(entity.Id));
Можно использовать уже готовый метод GetByIdAsync

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +        _dbContext = dbContext ?? throw new ArgumentNullValueException(nameof(dbContext));
Можно использовать просто ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
> +    where TKey : notnull, IEquatable<TKey>
Сделать проверку на приметивный тип

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +public abstract class AbstractInMemoryRepository<TEntity, TKey>
Почему класс абстрактный, если в нём ничего абстрактного нет?

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +    where TKey : notnull, IEquatable<TKey>
Сделать проверку на приметивный тип

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
> +            ?? throw new ArgumentNullValueException(nameof(entities));
Можно использовать просто ArgumentNullException или сохранять в качестве объекта пустую коллекцию, что лучше

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
> +        Money = money ?? throw new ArgumentNullValueException(nameof(money));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
> +        FromBill = fromBill ?? throw new ArgumentNullValueException(nameof(fromBill));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
> +        ToBill = toBill ?? throw new ArgumentNullValueException(nameof(toBill));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
> +        Lot = lot ?? throw new ArgumentNullValueException(nameof(lot));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
> +        Id = id;
Добавить проверку на Id, что оно не является Guid.Empty

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
> +    }
Использовать уже написанный более детальный конструктор

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Owner.cs
> +        Bill = bill ?? throw new ArgumentNullValueException(nameof(bill));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Freezing.cs
> +        Bill = bill ?? throw new ArgumentNullValueException(nameof(bill));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Freezing.cs
> +        Money = money ?? throw new ArgumentNullValueException(nameof(money));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Freezing.cs
> +        Lot = lot ?? throw new ArgumentNullValueException(nameof(lot));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Freezing.cs
> +        Id = id;
Добавить проверку на Id, что оно не является Guid.Empty

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        Owner = owner ?? throw new ArgumentNullValueException(nameof(owner));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        Money = money ?? throw new ArgumentNullValueException(nameof(money));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        FrozenMoney = frozenMoney ?? throw new ArgumentNullValueException(nameof(frozenMoney));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        _transfers = transfers ?? throw new ArgumentNullValueException(nameof(transfers));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        _freezings = freezings ?? throw new ArgumentNullValueException(nameof(freezings));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        Id = id;
Добавить проверку на Id, что оно не является Guid.Empty

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/ValueObject.cs
В этот класс добавить также операторы сравнения и арифметические операторы, так как они используются в дальнейшем коде, и лучше логику возможности добавления/вычитания и так далее иметь здесь, также как и логику сравнения по модулю

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        }
Перенести логику сравнения в ValueObject

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        }
Перенести логику сравнения в ValueObject

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        }
Перенести логику сравнения в ValueObject

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        FrozenMoney = new Money(FrozenMoney.Value - money.Value);
Перенести логику сложения и вычитания в ValueObject

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        if (transfer == null) throw new ArgumentNullValueException(nameof(transfer));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException, либо вообще убрать эту проверку, так как проверка на null есть в конструкторе, а EF скорее всего передаст пустую коллекцию, чем null, также можно изначально инициализировать пустой коллекцией

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        if (freezing == null) throw new ArgumentNullValueException(nameof(freezing));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        if (_freezings == null) throw new FieldNullValueException(nameof(_freezings));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException, либо вообще убрать проверку, так как есть проверка на это в конструкторе, а EF передаст скорее всего пустую коллекцию, чем null, либо вообще изначально самому инициализировать пустой коллекцией

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +    public Money FreeMoney => new Money(Money.Value - FrozenMoney.Value);
Перенести логику вычитания в ValueObject

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        ?? throw new FieldNullValueException(nameof(_transfers));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException, либо вообще убрать проверку, так как есть проверка на это в конструкторе, а EF передаст скорее всего пустую коллекцию, чем null, либо вообще изначально самому инициализировать пустой коллекцией

2024-08-23 11:12 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Bill.cs
> +        ?? throw new FieldNullValueException(nameof(_freezings));
Здесь лучше какое-нибудь доменное исключение, наследованное от ArgumentNullException, либо вообще убрать проверку, так как есть проверка на это в конструкторе, а EF передаст скорее всего пустую коллекцию, чем null, либо вообще изначально самому инициализировать пустой коллекцией

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/TextNullValueException.cs
> +    : DomainValidationException("Text cannot be null");
Не очень понятное исключение, хочется деталей, какой текст, откуда текст и почему не может быть null

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/TextEmptyValueException.cs
> +public class TextEmptyValueException(string value)
Опять же хочется деталей откуда и какой текст не может быть null

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/NameNullValueException.cs
> +    : DomainValidationException("Name cannot be null");
Лучше назвать PersonNameNullException, а также передать объект, где это встретилось

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/NameLongValueException.cs
> +        $"The line must be no longer than {maxLength} characters, the passed value is \"{value}\"");
Аналогично лучше назвать PersonNameLongException, а также передать где именно это встретилось

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/NameEmptyValueException.cs
> +        $"The name cannot be an empty string or a space, the passed value is \"{value}\"");
Лучше назвать PersonNameEmptyException, а также передать откуда такое встретилось

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/MoneyValueException.cs
> +        $"The money value cannot be less than 0, the passed value is: {value}");
Лучше назвать MoneyNegativeValueException, и передать откуда это встретилось

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/FieldNullValueException.cs
> +        $"Field \"{fieldName}\" value is null");
Максимально непонятное и неконкретное исключение, либо его убрать вообще, либо передать больше параметров и конкретизировать, наследовав, например, от FormatException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/MoneyValueException.cs
> +        $"The money value cannot be less than 0, the passed value is: {value}");
Также следует наследовать от FormatException

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/DomainValidationException.cs
> +public class DomainValidationException(string message) : DomainException(message);
Максимально неконкретное исключение, его стоит убрать

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/DomainStateException.cs
> +public class DomainStateException(string message) : DomainException(message);
Максимально непонятное и неконкретное исключение, его просто надо убрать

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/DomainException.cs
> +public class DomainException(string message) : Exception(message);
Смысл этого исключение? По сути оно ровно такое же как системное, просто с другим названием. Такое исключение надо брать, так как оно не имеет смысла

2024-08-23 11:12 UTC, oleggolen commented on src/Common/Auction.Common.Domain/Exceptions/ArgumentNullValueException.cs
> +        $"Argument \"{argumentName}\" value is null");
Можно наследовать просто от ArgumentNullExceptuin и дать более деталей и конкретики, что и где null

2024-08-23 11:12 UTC, oleggolen commented on src/Auction.WalletMicroservice.Infrastructure.EntityFramework/ApplicationDbContext.cs
> +    public DbSet<Freezing> Freezings { get; set; }
На сколько я знаю в финансовой области именно так и называется, поэтому я не против такого

2024-08-23 13:20 UTC, m-a-ilnitsky commented on src/Auction.WalletMicroservice.Infrastructure.EntityFramework/Configurations/FreezingConfiguration.cs
> +        builder.HasOne(f => f.Bill).WithMany("_freezings");
Продублирую здесь:
По поводу строк в конфигурации флуэнт апи - это возникает из-за того что поле не публичное и его нельзя достать лямбдой.
И константа в данном случае не решает проблему, т.к. имя поля не будет зависеть от константы.
builder.HasMany<Transfer>("_transfers") - если здесь строку заменить на константу, то изменение имени поля все равно потребует дополнительно изменять значение константы. В этом случае литерал строки указанный в конфигурации сущности легче не забыть поменять, чем константу указанную где-то вовне.
Можно конечно сделать в самой сущности свойство с именем поля, например, так:
private ICollection<Transfer>? _transfers;
public static string TransfersFieldName => nameof(_transfers);
Тогда изменение имени свойства будет автоматом менять TransfersFieldName.
Если TransfersFieldName сделать нестатическим то нужно будет предотвращать создание столбца для этого поля в БД и вызов этого поля будет выглядеть как типичная запись обращения к свойству в флуэнт апи, возможно EF не сможет использовать его значение.
Если TransfersFieldName сделать статическим, то тогда вместо builder.HasMany<Transfer>("_transfers") можно будет написать так:
builder.HasMany<Transfer>(Bill.TransfersFieldName)
Но этот вариант мне тоже не нравится, т.к. в сущности появляются лишние свойства.
В общем, уж лучше пусть будет строковый литерал, по которому и так все понятно

2024-08-26 19:53 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/Exceptions/MoneyValueException.cs
> +        $"The money value cannot be less than 0, the passed value is: {value}");
Здесь не согласен.
Все известные мне примеры FormatException связаны с парсингом строки в какое-то значение, когда в строке ожидаются одни символы, а оказываются другие.
Например, если пытаться парсить "True" в число, или "Ура!" в bool, или  "1e-16" в DataTime.
Здесь нет строки, и здесь нет возможности передать число в каком то ином формате, чем предполагает конкретный числовой тип

2024-08-26 19:55 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/Exceptions/MoneyValueException.cs
> +        $"The money value cannot be less than 0, the passed value is: {value}");
Я думаю здесь нужно наследоваться либо от ArgumentException, либо от ArgumentOutOfRangeException

2024-08-26 20:04 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/Exceptions/NameEmptyValueException.cs
> +        $"The name cannot be an empty string or a space, the passed value is \"{value}\"");
Здесь не получится передать откуда пришла строка, т.к. это исключение бросается внутри конструктора валуэ-обджекта, а в него не передаем имена аргументов извне

2024-09-05 10:13 UTC, closed without merging