Fix/gd 176 fix entities
IT-Siberians/WalletMicroservice pull request #3
Opened 2024-08-31 20:13 UTC by m-a-ilnitsky

Пул реквест для проверки двух веток 174 и 176 в Кошельке, а также 175 и 177 в Архиве.
Т.к. большая часть кода в них идентична, и логика его формирования идентична, то сейчас делаю пул-реквест только для Кошелька, чтобы не просматривать одинаковый код дважды

I. Исправил иерархию исключений - унаследовал исключения домена не от собственного корня, а от стандартных исключений

II. Исправил замечания по  Entity и ValueObject:

1) Для TKey в IEntity сделал ограничение struct
2) Добавил интерфейс IDeletableSoftly для мягкого удаления пользователя
3) ValueObject Name заменил на два: PersonName и Title (чтобы заголовок задавался как у Яны)
4) ValueObject PersonName задал диапазон длин строки и добавил валидацию регулярным выражением как сделано у Константина и Николая
5) Сделал базовый класс NumericObject для числовых ValueObject, с перегрузкой операторов сравнения
6) Добавил в ValueObject Money операторы сравнения/вычитания
7) Добавил ValueObject Price, чтобы цены не могли быть равны нулю, чтобы была такая же логика валидации цен как у Яны
8) Подавил предупреждения вызванные наличием конструктора для EF

2024-09-04 10:49 UTC, Barmalej24 approved these changes

2024-09-04 12:29 UTC, NikeTorchwood approved these changes
нет замечаний

2024-09-18 06:59 UTC, oleggolen requested changes
Не могу принять из-за достаточно больших проблем в логики работы с деньгами, но во всём остальном просто отличный код, мне очень понравился и это именно то, что я хотел видеть изначально

2024-09-18 06:59 UTC, oleggolen commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
Не очень могу понять почему источник и приёмник транзакции nullable, а также лот, по которому идёт транзакция, по идеи они не могут быть null по правилам, иначе транзакция смысла не имеет

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
>      }
Можно использовать primary конструктор

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/Ef/AbstractEfRepository.cs
>              .Set<TEntity>()
Можно использовать уже написанный метод, так получается дублирование кода

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/Abstract/ValueObject.cs
>          }
Зачем тут nullable?

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/Numeric/Money.cs
> +    public static bool IsValid(decimal value) => value >= 0;
В валидации лучше проверять знаки после запятой или где-то в логике иметь округление по модулю, так как ситуация 0,000000007 для нас не приемлема в данном случае

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/Numeric/Money.cs
> +        => new(left.Value - right.Value);
Тут стоит вычитать по модулю или как-то проверять на корректность потому что в случае некорректного вычитания мы получаем исключение и падение программы

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjects/Numeric/Price.cs
> +        if (value <= 0) throw new PriceNonPositiveValueException(value);
Опять же нужна проверка с округлением, так как 0.00000007 это больше нуля, но нас волнуют только 2 знака после запятой, очевидно, что лот не может быть бесплатным

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjectsExceptions/PersonNameFormatException.cs
> +        $"The name is in the wrong format, the passed value is \"{value}\"");
Лучше добавить информацию о корректном формате

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjectsExceptions/TextEmptyValueException.cs
>          $"The text cannot be an empty string or a space, the passed value is \"{value}\"");
Тут лучше использовать ArgumentNullExcepion или ArgumentNullValueException, так как для нас сценарии, когда пользователь передал пустую строку или null практически не различаются по доменным правилам

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjectsExceptions/TitleEmptyValueException.cs
> +        $"The title cannot be an empty string or a space, the passed value is \"{value}\"");
Аналогично с предыдущими

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/ValueObjectsExceptions/ValidationInconsistencyException.cs
> +    : Exception("Inconsistency between Validate and IsValid methods");
Вообще не понимаю, что имеется в виду под этим исключением

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/EntitiesExceptions/ArgumentNullValueException.cs
>          $"Argument \"{argumentName}\" value is null");
А для чего нужно это исключение? Есть же похожие исключения только для более конкретных параметров

2024-09-18 06:59 UTC, oleggolen commented on src/Common/Auction.Common.Domain/EntitiesExceptions/FieldNullValueException.cs
>          $"Field \"{fieldName}\" value is null");
Максимально непонятное исключение, по идеи сценариев, когда у нас поле оказалось null быть не должно, так как это будет либо отсеяно в конструкторе, либо где-то в процессе логики либо получит значение либо будет отсеяно

2024-09-18 08:17 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/ValueObjects/Abstract/ValueObject.cs
>          }
Потому что в метод можно передать null, т.к. аргумент ссылочного типа.
И сейчас туда передастся null если в Equals(obj as ValueObject<T>) значение obj будет null или будет неподходящего типа

2024-09-18 08:19 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/EntitiesExceptions/ArgumentNullValueException.cs
>          $"Argument \"{argumentName}\" value is null");
Это исключение для доменных сущностей, когда в конструктор или метод передали null вместо агрумента

2024-09-18 08:20 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/EntitiesExceptions/FieldNullValueException.cs
>          $"Field \"{fieldName}\" value is null");
Ну у нас еще есть конструктор для EF и если EF будет настроен неправильно, то навигационное свойство может оказаться равно null

2024-09-18 08:28 UTC, m-a-ilnitsky reviewed
---

2024-09-18 08:28 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/ValueObjects/Numeric/Money.cs
> +        => new(left.Value - right.Value);
Именно поэтому я исходно был против добавления этих операторов.
Но вычитать по модулю здесь неправильно, это будет сокрытие ошибки.
Но в итоге сделал операторы, из таких соображений: фактически здесь будет брошено исключение только если где-то в логике доменных сущностей будет допущена ошибка, так что это не страшно, это только дополнительная проверка на логику доменных сущностей

2024-09-18 08:28 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/ValueObjects/Numeric/Money.cs
> +    public static bool IsValid(decimal value) => value >= 0;
Ну тут до конца не понятно как действовать, факически нам с Яной нужно договориться как обрабатывать эту ситуацию одинаково.
Я предлагал в конструкторе денег выполнять округление до второго знака.
Но Яне этот вариант почему-то не понравился

2024-09-18 08:37 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/ValueObjectsExceptions/TextEmptyValueException.cs
>          $"The text cannot be an empty string or a space, the passed value is \"{value}\"");
По доменным правилам не различаются, а по причинам, почему это значение было передано, null и пустая строка сильно отличаются, поэтому лучше их не смешивать, тогда по сообщению будет понятнее в чем причина ошибки

2024-09-18 08:39 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Domain/ValueObjectsExceptions/ValidationInconsistencyException.cs
> +    : Exception("Inconsistency between Validate and IsValid methods");
Если при изменении кода, методы Validate и IsValid окажутся несогласованными, то будет брошено это исключение

2024-09-18 08:45 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Infrastructure/RepositoriesImplementations/InMemory/AbstractInMemoryRepository.cs
>      }
Да, студия пишет про это.
Но код получается корявый, мне не понравилось как это выглядит.
Когда у конструктора нет своей логики и только дергается базовый конструктор, то примари конструктор выглядит очень хорошо.
Но в этом случае классический вариант читается явно лучше

2024-09-18 08:47 UTC, m-a-ilnitsky commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
Я исходно говорил, что для зачисления/вывода денег на/с кошелька во вне буду считать что кошелёк в этом случае будет null.
Т.е. когда один из счетов транзакции null, это перевод денег между кошельком и внешним миром.
Это сделано для простоты, чтобы не пришлось городить таблицы внешних банковских счетов/карт и т.д.
И там поэтому у перевода два конструктора, один для перевода между кошельками, а другой для зачисления/снятия денег с кошелька.
И лот тоже не нужен, если перевод между кошельком и внешним миром

2024-09-18 08:48 UTC, m-a-ilnitsky commented on src/Domain/Auction.WalletMicroservice.Domain/Entities/Transfer.cs
Понятно, что для снятия/пополнения в реальности пришлось бы делать отдельную таблицу, но не хочется городить это в учебном проекте, поэтому для простоты все сделано через таблицу переводов между кошельками

2024-09-28 19:43 UTC, closed without merging