GD-180 Added UnitOfWork
IT-Siberians/WalletMicroservice pull request #5
Opened 2024-09-03 01:52 UTC by m-a-ilnitsky

Добавлен UnitOfWork в микросервис Кошелька.
Эти изменения уникальны для микросервиса Кошелька.

2024-09-03 10:57 UTC, Barmalej24 approved these changes

2024-09-04 11:21 UTC, NikeTorchwood commented on src/Infrastructure/Auction.WalletMicroservice.Infrastructure.RepositoriesImplementations/EntityFramework/EfUnitOfWork.cs
> +        Transfers = new BaseEfRepository<ApplicationDbContext, Transfer, Guid>(_dbContext);
аналогично сервису лотов, считаю нарушение 5го принципа

2024-09-04 11:21 UTC, NikeTorchwood requested changes
Аналогично сервису лотов, считаю нарушение принципов солид в коде, думаю можно исправить

2024-09-18 07:19 UTC, oleggolen requested changes
Не очень могу понять в чём идея всех этих действий

2024-09-18 07:22 UTC, closed without merging