GD-171 Added application services
IT-Siberians/WalletMicroservice pull request #8
Opened 2024-10-10 21:00 UTC by m-a-ilnitsky

Добавление слоя бизнес-логики

2024-10-11 20:52 UTC, oleggolen requested changes
В целом достаточно неплохо, но очень переусложнённая логика, и лучше что-то вынести на уровень ниже,  большую чась валидации перенести на уровень выше, и лучше просто реализовывать бизнес-логику приложения, основываясь на моделях приложения, проверять и мёрджить и вызывать что-то уровня домена, а в случаях, что можно проверить на уровне представления лучше просто кидать исключения, если не получается так, то просто что-то более аккуратное возвращать

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/OwnerIdModel.cs
> +public record OwnerIdModel(Guid OwnerId);
Смысл от этой записи?

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    public string TypeName => Enum.GetName(Type) ?? Type.ToString();
Здесь лучше сделать строку required

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    public BalanceModel? Balance { get; set; }
Наверное его лучше сделать {get; init;}

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    LotInfoModel? Lot)
Мне кажется в этом смысле это null точно не может быть, так как у нас все транзакции совершаются по какому-то лоту

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    public string TypeName => Enum.GetName(Type) ?? Type.ToString();
И лучше тогда сразу использовать Enum

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/Responses/Response.cs
> +}
Лучше это всё делать на уровне представления, да и вообще ответы на запросы это модель уровня представления

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/Responses/BaseResponse.cs
> +}
Перенести куда-нибудь на уровень представления, или как-то переименовать, потому что эта логика и названия явно уровня выше

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesAbstractions/IOwnerService.cs
> +        CancellationToken cancellationToken = default);
Тут лучше просто возвращать типы моделей уровня приложений, а не такие ответы, так как эта логика больше похожа на участки уровня представления

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesAbstractions/ITraidingService.cs
> +        CancellationToken cancellationToken = default);
Тут лучше просто возвращать типы моделей уровня приложений, а не такие ответы, так как эта логика больше похожа на участки уровня представления

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/OwnerService.cs
> +﻿using Auction.Common.Application.Models.Common;
Ужасно много кода, возможно можно как-то это рабить на сервисы поменьше или паттерны, также обработку ошибок или что-то такое стоит вынести на уровень представления

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/TraidingService.cs
> +public class TraidingService(
Всё то же что и про OwnerService, возможно стоит подумать в сторону CQRS, команд и запросов и воспользоваться паттерном MediatR, потому что супер много кода и очень много логики, которую можно на уровень представления перетащить

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/ServicesImplementations/PersonService.cs
> +public class PersonService<TPerson, TPersonRepository>(
Тоже часть логики можно поднять на уровень выше, и подумать про разделение сервисов

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/ModelsValidators/PersonInfoValidator.cs
> +}
Убрать отсюда

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/ModelsValidators/PersonIdValidator.cs
> +}
Убрать отсюда

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/ModelsValidators/LotInfoValidator.cs
> +﻿using Auction.Common.Application.Models.Common;
Убрать отсюда

2024-10-11 20:52 UTC, oleggolen commented on src/Common/Auction.Common.Application/ModelsValidators/IModelValidator.cs
> +}
Здесь они не нужны

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/ModelsValidators/MoveMoneyValidator.cs
> +}
Перенести на уровень выше

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/ModelsValidators/OwnerIdValidator.cs
> +    }
Перенести на уровень выше

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/ModelsValidators/PayForLotValidator.cs
> +}
Перенести на уровень выше

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/ModelsValidators/RealeaseMoneyValidator.cs
> +}
Перенести на уровень выше

2024-10-11 20:52 UTC, oleggolen commented on src/Application/Auction.WalletMicroservice.Application.Models/ModelsValidators/ReserveMoneyValidator.cs
> +}
Перенести на уровень выше

2024-10-12 20:00 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Models/ModelsValidators/MoveMoneyValidator.cs
> +}
@oleggolen 
А разве проверка, что, например, деньги не должны быть отрицательными, а цены должны быть строго больше ноля - это не уровень бизнес логики?
Я думал, что на уровне представления мы проверяем только что все обязательные поля заполнены

2024-10-12 20:05 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/OwnerIdModel.cs
> +public record OwnerIdModel(Guid OwnerId);
@oleggolen 
Если бы передавался просто Guid, то его валидацию нужно было бы делать как-то иначе, не с помощью валидаторов моделей.
Благодаря этой записи удается выполнить валидацию Id единообразно с другими dto.
Т.е. это только для упрощения валидации

2024-10-12 20:08 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    LotInfoModel? Lot)
@oleggolen 
Это общая модель для всех вариантов транзакций.
И для заморозки денег, для оплаты лота, и для ввода/вывода денег из кошелька.
Для ввода/вывода денег из кошелька транзакции не связаны ни с каким лотом

2024-10-12 20:16 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    public string TypeName => Enum.GetName(Type) ?? Type.ToString();
@oleggolen 
Это замечание я не понял.
Этот код выводит само название значения Enum'а, просто для информативности.
На фронте в Swagger'е поле Type будет выведено как 0 или 1 или 2 или 3, и т.д., т.к. в JS нет enum'ов.
А поле TypeName вместо 0 будет содержать строку "PutMoney".
Это более информативно.
Вот пример:
    {
      "transferMoney": 1000,
      "freezingMoney": null,
      "dateTime": "2024-10-12T20:14:16.019801Z",
      "type": 0,
      "lot": null,
      "typeName": "PutMoney",
      "balance": {
        "allMoney": 1000,
        "frozenMoney": 0,
        "freeMoney": 1000
      }
    }

2024-10-12 20:20 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Models/Owner/TransactionModel.cs
> +    public BalanceModel? Balance { get; set; }
@oleggolen 
Я это поле специально отдельно объявил, т.к. оно вычисляется после того как созданы и отсортированы по времени все экземпляры TransactionModel.
Если сделать его init, то придется полностью пересоздавать все экземпляры TransactionModel для добавления значения этого поля

2024-10-12 20:30 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesAbstractions/IOwnerService.cs
> +        CancellationToken cancellationToken = default);
@oleggolen 
Категорически не согласен.
Как в таком случае возвращать ошибки из уровня приложения?
Если бросать исключение и потом ловить это исключение в представлении, то это будет просадка производительности в сотни раз.
И тогда нельзя будет вернуть сразу несколько ошибок.
На уровне бизнес-логики нужно делать очень много проверок (существует ли пользователь/лот с таким id, разрешено ли пользователю выполнить эту операцию и т.д. и т.п.), которые по своему смыслу относятся к уровню бизнес-логики.
Это самый простой и очевидный способ вернуть эти ошибки без лишних накладных расходов на бросание исключений

2024-10-12 20:50 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/OwnerService.cs
> +﻿using Auction.Common.Application.Models.Common;
@oleggolen 
Здесь на уровень представления получится вынести только обработку сводящуюся к этой строке кода:
var errors = _...Validator.GetErrors(model);
Все остальные проверки в сервисах привязаны к результатам запросов к базе данных или к результатам работы доменных методов, поэтому большую часть этого кода не получится перенести на уровень представления

2024-10-12 20:57 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/OwnerService.cs
> +﻿using Auction.Common.Application.Models.Common;
Обычно сервисы просто вызывают хэндлеры, т.е. вся эта логика выносится из самих сервисов, но по смыслу это ничего не меняет, просто на каждый метод сервиса создаётся отдельный класс хэндлера, т.е. кода остаётся столько же, но он разбит на несколько классов.
Мне что ли на эндлеры код разбить?

2024-10-12 20:57 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/OwnerService.cs
> +﻿using Auction.Common.Application.Models.Common;
И естественно, что чем больше таблиц БД использует метод, тем больше в нём будет всяких разных проверок

2024-10-12 21:02 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/TraidingService.cs
> +public class TraidingService(
@oleggolen 
Про CQRS и MediatR не понял, тут нужно пояснение

2024-10-12 21:03 UTC, m-a-ilnitsky commented on src/Application/Auction.WalletMicroservice.Application.Services/ServicesImplementations/TraidingService.cs
> +public class TraidingService(
И конкретно этот сервис содержит только команды, т.е. тут не получится запросы вынести в другой сервис

2024-10-12 21:10 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Application/Responses/BaseResponse.cs
> +}
@oleggolen 
Название тут не причём.
Если не нравится слово Response (хотя я не считаю, что его можно использовать только в представлении) можно назвать Report или Answer.
Но должна быть возможность вернуть ошибку (или набор ошибок) без использования исключений.
Не все ошибки можно отловить на уровне представления.
Большая часть ошибок это как раз уровень бизнес логики или домена

2024-10-12 21:13 UTC, m-a-ilnitsky commented on src/Common/Auction.Common.Application/ServicesImplementations/PersonService.cs
> +public class PersonService<TPerson, TPersonRepository>(
@oleggolen 
Сервисы уже разделены по максимуму, дальше получится по одному методу на сервис.
Можно логику методов вынести в хэндлеры, в ни как раз по смыслу по одному методу

2024-10-13 00:47 UTC, m-a-ilnitsky commented
> В целом достаточно неплохо, но очень переусложнённая логика, и лучше что-то вынести на уровень ниже, большую чась валидации перенести на уровень выше, и лучше просто реализовывать бизнес-логику приложения, основываясь на моделях приложения, проверять и мёрджить и вызывать что-то уровня домена, а в случаях, что можно проверить на уровне представления лучше просто кидать исключения, если не получается так, то просто что-то более аккуратное возвращать

В моём понимании на уровне представления можно валидировать заполнение полей, т.е. то что отноистся не к бизнес-логике, а к передаче данных.
Например, что строка не null и не пустая, для обязательных строковых полей.
Что массив не пустой, если он обязан быть непустым.
Что Id не равен 0 (для int) или Guid.Empty (для Guid).

Да, проверку, что сумма денег не отрицательная можно выполнить и в представлении.
Или проверку формата заголовка лота, или имени пользователя.
Это просто сделать за счёт того что есть метод IsValid у доменных объектов, который легко вызвать в представлении.
Но я не уверен, что это имеет смысл делать именно в представлении, т.к. по смыслу это проверка доменных правил, т.е. часть бизнес-логики.
И если вынести эти правила в представление, то бизнес-логика получится размазана между слоями представления и приложения.
Если бизнес-логика не будет сосредоточена в одном месте это усложнит ее понимение.

В целом в моём понимании самая сложная валидация относится как раз к бинес логике.

Например, варианты проверки одних полей могут зависеть от значений других полей:
- есть поля с данными паспорта, но паспорт может быть и внутренним и заграничным, тогда проверка полей ФИО будет зависеть от типа паспорта, для внутреннего все символы ФИО должны быть кириллическими, для загранника латинскими, т.е. проверка одного поля зависит от значения другого поля
- или формат номера паспорта может зависеть от того пасспорт какого государства имеет пользователь
- или в зависимости от поля пользователя нужно проверить что отчество заканчивается на "вич" или на "вна"
- или в зависимости от сочетания гражданства и возвраста пользователя ему могут быть недоступны какие-то услуги сайта
Да, такие проверки удастся вынести на уровень представления, но имеет ли смысл это делать?
Особенно если представлений несколько и тогда проверки нужно будет дублировать в каждом представлении, вместо того чтобы реализовать их один раз в сервисе приложения

Если же проверка зависит от предыдущих действий пользователя (например, добавил он ранее паспортные данные/ИНН/фотографию/почту/телефон/ или оплатил нужный тариф), то ее вообще не удастся вынести на уровень представления.
При этом формат возвращаемого ответа не должен принципиально отличаться от других проверок бизнес-логики, которые вынести на уровень представления всё-таки возможно.
Поэтому я считаю, что все проверки обусловленные бизнес-логикой должны быть на уровне бизнес-логики

2024-10-13 00:51 UTC, m-a-ilnitsky commented
> В целом достаточно неплохо, но очень переусложнённая логика, и лучше что-то вынести на уровень ниже, большую чась валидации перенести на уровень выше, и лучше просто реализовывать бизнес-логику приложения, основываясь на моделях приложения, проверять и мёрджить и вызывать что-то уровня домена, а в случаях, что можно проверить на уровне представления лучше просто кидать исключения, если не получается так, то просто что-то более аккуратное возвращать

@oleggolen 
Я сделал три самодостаточных сервиса, которые пока используются только в http-контроллерах, но инкапсулируют в себе всю необходимую логику, чтобы точно также использоваться в RabbitMQ или в gRPC.
Но предполагается, что из трёх сервисов в итоге только один длжен работать с http, второй должен использоваться в RabbitMQ, а третий в gRPC
Если сейчас вынести валидацию на уровень представления, то эту логику валидации придется дублировать.
Возможно (хотя не уверен), что для RabbitMQ удастся использовать те же модели, что и для http и переиспользовать валидацию.
Но в gRPC совершенно точно будут другие модели и валидацию придется делать отдельно.
На мой взгляд это тоже веский повод для того чтобы валидация связанная с бизнес-логикой была в слое бизнес-логики.
А в представлении отсавить только отлавливание всях null и  пустых строк

2024-10-13 00:56 UTC, m-a-ilnitsky commented
> В целом достаточно неплохо, но очень переусложнённая логика, и лучше что-то вынести на уровень ниже, большую чась валидации перенести на уровень выше, и лучше просто реализовывать бизнес-логику приложения, основываясь на моделях приложения, проверять и мёрджить и вызывать что-то уровня домена, а в случаях, что можно проверить на уровне представления лучше просто кидать исключения, если не получается так, то просто что-то более аккуратное возвращать

Я не согласен с тем что методы контроллера слишком сложные и длинные (кроме метода возвращающего список транзакций, да, он по смыслу сложный и не имеет отношения к домену, поэтому его сложность не скрывается доменными сущностями).

За счёт того что большая часть логики инкапсулирована в доменном слое, методы сервисов получились короче чем обычно.
В сервисах осталась только работа с БД и всяческие проверки связанные с этой работой.
Да если бы у меня была одна таблица на микросервис, вся эта логика сводилась бы к одной проверке, что нужная запись в таблице есть (собственно так и выглядит PersonService, который работает только с одной таблицей).
Но т.к. таблиц много то логика работы с таблицами становится сложной.
И эту сложность не получится скрыть в домене, не позволив домену самостоятельно работать с базой.

В целом, я думаю бывает куча высоконагруженных сайтов у которых фактически нет бизнес логики, и тогда там действительно методы сервисов получаются очень простые.
Например, сайт для выдачи картинки по её id очевидно не будет иметь никакой сложной бизнес-логики, но при этом будет очень высоконагруженным.
С другой стороны в большинство бизнес-процессов имеют настолько сложную логику, что хочется застрелиться или застрелить того кто эту логику придумал.

Кошелёк по своему смыслу имеет эту самую бизнес логику и от нее не избавиться (хотя в моём понимании она достаточно простая, в том числе потому что я хотел её по-максимуму упростить).

Да, я могу логику каждого метода каждого сервиса вынести в отдельный хэндлер, тогда методы сервиса сведутся только к дёрганию методов хэндлера.
Но ранее вы говорили, что никакие хэндлеры не нужны и код можно писать прямо в методах сервисов.
Если же всё-таки выносить код в хэндлеры, то лучше вообще отказаться от сервисов и вызвать в методах контроллера сразу нужные хэндлеры, т.к. тогда для их получения можно будет использовать DI, и не делать танцы с бубном (сервис-локатором)

2024-11-02 14:10 UTC, closed without merging