GD-224 Added WebAPI
IT-Siberians/WalletMicroservice pull request #9
Opened 2024-10-10 21:02 UTC by m-a-ilnitsky

Добавление слоя представления (WebAPI) Кошелька

2024-10-11 10:01 UTC, Barmalej24 approved these changes
Код понравился! В целом только пожелания возможные для реализации.. Добавить и использовать FluentValidation для проверки входящих Dto

2024-10-11 10:01 UTC, Barmalej24 commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Program.cs
> +builder.Services.AddSwaggerGen();
добавить описательную часть.

2024-10-11 10:01 UTC, Barmalej24 commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Program.cs
> +        builder.Configuration.GetConnectionString("DefaultConnection"),
добавить проверку на наличие строки подключения

2024-10-11 10:01 UTC, Barmalej24 commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/appsettings.Development.json
добавить в игнор

2024-10-11 10:01 UTC, Barmalej24 commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/appsettings.json
настройки лучше хранить в *.Development.json

2024-10-11 10:01 UTC, Barmalej24 commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Contracts/LotInfoRequestData.cs
> +public record LotInfoRequestData(
последовательность наименования не нарушена?

2024-10-11 19:28 UTC, m-a-ilnitsky commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Contracts/LotInfoRequestData.cs
> +public record LotInfoRequestData(
Не знаю как тут правильнее поступить.
Возможно лучше было назвать по простому: LotInfoDto

2024-10-11 21:02 UTC, oleggolen requested changes
Да тут в целом всё хорошо, я бы перенёс сюда валидацию, также бы добавил возвращаемые статус коды у ответов, в них какие-то вложенные данные, также соответствующие аттрибуты, показывающие какой статус код и когда возвращается, больше подробной информации в сваггер, чтобы сразу было понятно для фронта, что и когда и при каких условиях возвращается, можно даже добавть документацию к API методам. Всю валидацию вынести с помощью FluentValidation или с помощью аттрибутов и этот механизм ответов, который сейсас реализован в уровне бизнес-логики будет поддержан из коробки соответствующей библиотекой.

2024-10-11 21:02 UTC, oleggolen commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/appsettings.Development.json
Согласен

2024-10-11 21:02 UTC, oleggolen commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/appsettings.json
Соглаасен

2024-10-11 21:02 UTC, oleggolen commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Program.cs
> +        builder.Configuration.GetConnectionString("DefaultConnection"),
Согласен

2024-10-11 21:02 UTC, oleggolen commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Program.cs
> +builder.Services.AddSwaggerGen();
Согласен

2024-10-11 21:02 UTC, oleggolen commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/Contracts/LotInfoRequestData.cs
> +public record LotInfoRequestData(
Просто убрать слово Data

2024-10-12 21:15 UTC, m-a-ilnitsky commented on src/Presentation/Auction.WalletMicroservice.Presentation.WebApi/appsettings.Development.json
А как вы будете его запускать тогда?

2024-11-02 14:10 UTC, closed without merging